/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanager;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vishal
 */
public class Sales_Manager extends javax.swing.JFrame {

    /**
     * Creates new form Sales_Manager
     */
    public Sales_Manager() {
        
        initComponents();
        table();
        bills();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        transaction = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        total_transaction = new javax.swing.JLabel();
        sal_man_submit3 = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        date_list = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        bill_table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        total_transaction_per_day = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        sel_man_yes = new javax.swing.JButton();
        sel_man_no = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        label13 = new java.awt.Label();
        label10 = new java.awt.Label();
        label12 = new java.awt.Label();
        label11 = new java.awt.Label();
        sal_man_reset2 = new java.awt.Button();
        sal_man_submit2 = new java.awt.Button();
        status1 = new javax.swing.JLabel();
        status2 = new javax.swing.JLabel();
        Existing_password = new javax.swing.JPasswordField();
        New_password = new javax.swing.JPasswordField();
        Confirm_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Manager");

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("Transactions...");

        transaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill name", "Product Name", "Date", "Quantity", "Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        transaction.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(transaction);
        transaction.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel1.setText("Total transactions");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(total_transaction)
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(total_transaction))
                .addContainerGap())
        );

        label1.getAccessibleContext().setAccessibleName("");

        jTabbedPane1.addTab("Total Money Transaction", jPanel1);

        label3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label3.setText("Enter Bill Date...");

        label4.setText("Date");

        date_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_listActionPerformed(evt);
            }
        });

        bill_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Bill name", "Date", "Transaction"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(bill_table);

        jLabel2.setText("Total transaction per day:");

        javax.swing.GroupLayout sal_man_submit3Layout = new javax.swing.GroupLayout(sal_man_submit3);
        sal_man_submit3.setLayout(sal_man_submit3Layout);
        sal_man_submit3Layout.setHorizontalGroup(
            sal_man_submit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sal_man_submit3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sal_man_submit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sal_man_submit3Layout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sal_man_submit3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(total_transaction_per_day)
                .addGap(161, 161, 161))
        );
        sal_man_submit3Layout.setVerticalGroup(
            sal_man_submit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sal_man_submit3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sal_man_submit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(sal_man_submit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(total_transaction_per_day))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label3.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane1.addTab("Bills Per Day", sal_man_submit3);

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel7.setText("Are you sure you want to logout?");

        sel_man_yes.setText("YES");
        sel_man_yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sel_man_yesActionPerformed(evt);
            }
        });

        sel_man_no.setText("NO");
        sel_man_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sel_man_noActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(sel_man_yes)
                        .addGap(54, 54, 54)
                        .addComponent(sel_man_no))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel7)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sel_man_yes)
                    .addComponent(sel_man_no))
                .addContainerGap(378, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Logout", jPanel4);

        label13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label13.setText("Change Password...");

        label10.setText("Existing Password");

        label12.setText("Confirm Password");

        label11.setText("New Password");

        sal_man_reset2.setLabel("Reset");
        sal_man_reset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sal_man_reset2ActionPerformed(evt);
            }
        });

        sal_man_submit2.setLabel("Submit");
        sal_man_submit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sal_man_submit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(status2)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(sal_man_submit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sal_man_reset2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(New_password, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(Confirm_password, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(Existing_password))
                                .addGap(140, 140, 140)
                                .addComponent(status1)))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Existing_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(status1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(New_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sal_man_submit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sal_man_reset2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                .addComponent(status2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Change Password", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sel_man_yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sel_man_yesActionPerformed
        // TODO add your handling code here:
        first fr=new first();
        dispose();
        fr.show();
    }//GEN-LAST:event_sel_man_yesActionPerformed

    private void sel_man_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sel_man_noActionPerformed
        // TODO add your handling code here:
        Sales_Manager sm=new Sales_Manager();
        dispose();
        sm.show();
    }//GEN-LAST:event_sel_man_noActionPerformed

    private void sal_man_submit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sal_man_submit2ActionPerformed
        // TODO add your handling code here:
            sqlconnect sql = new sqlconnect();
        try {
            Connection con;
            con = sql.Connections();
            Statement st = con.createStatement();
            String Query;
            String sel="select * from login where Name='sal_man'";
            ResultSet res=st.executeQuery(sel);
            while(res.next())
            {
            String pw=res.getString("Password");
            if(Existing_password.getText().equals(pw))
            {
            if (New_password.getText().equals(Confirm_password.getText())) {
                Query = "UPDATE login SET password='" + New_password.getText() + "' WHERE password='" + Existing_password.getText() + "' and Name='sal_man'";
                System.out.println(Query);
                int rs = st.executeUpdate(Query);
                if (rs > 0) {
                    status2.setText("Sucessfully updated");
                    status1.setText(" ");
                }
            } else {
                status1.setText("Password missmatch");
                status2.setText(" ");
            }
            }
            
            else{
             status2.setText("Invalid password");
            status1.setText(" ");
            Existing_password.setText(" ");
            New_password.setText(" ");
            Confirm_password.setText(" ");
                    }
            }
        } catch (Exception e) {
            /*status2.setText("Invalid password");
            status1.setText(" ");
            Existing_password.setText(" ");
            New_password.setText(" ");
            Confirm_password.setText(" ");*/
        }
    }//GEN-LAST:event_sal_man_submit2ActionPerformed

    private void sal_man_reset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sal_man_reset2ActionPerformed
        // TODO add your handling code here:
         Existing_password.setText(" ");
            New_password.setText(" ");
            Confirm_password.setText(" ");
    }//GEN-LAST:event_sal_man_reset2ActionPerformed

    private void date_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_listActionPerformed
        // TODO add your handling code here:
        total=0;
         sqlconnect sql=new sqlconnect(); 
        try
        {
        DefaultTableModel model = new DefaultTableModel();
        bill_table.setModel(model);
        model.setColumnIdentifiers(new Object[]{"Bill name","Date","Transaction"});
        Connection con;    
        con=sql.Connections();
        Statement st = con.createStatement();
        String Query;
        Query = "SELECT * from bill WHERE date='"+date_list.getSelectedItem()+"'";
        ResultSet res = st.executeQuery(Query); 
        while(res.next())
        {
            String bill_name= res.getString("bill_name");
                String date = res.getString("date");
                String trans = res.getString("transaction");
              model.addRow(new Object[]{bill_name,date,trans});
              total=total+Integer.parseInt(trans);
        }
        total_transaction_per_day.setText(String.valueOf(total));
         }catch (Exception e) 
         {
          e.printStackTrace();
         }
    }//GEN-LAST:event_date_listActionPerformed
int total=0;
    void table(){
        DefaultTableModel model = new DefaultTableModel();
        transaction.setModel(model);
        model.setColumnIdentifiers(new Object[]{"Bill name", "Product name", "Date", "Quantity", "Cost"});
        sqlconnect sql = new sqlconnect();
        try {
            Connection con;
            con = sql.Connections();
            Statement st = con.createStatement();
            String Query = "select * from transaction";
            ResultSet res = st.executeQuery(Query);
            while (res.next()) {
                String bill_name= res.getString("bill_name");
                String pro_name = res.getString("pro_name");
                String date = res.getString("date");
                String quantity = res.getString("quantity");
                String cost = res.getString("cost");
                System.out.println(quantity);
                total=total+Integer.parseInt(cost);    
        

                    model.addRow(new Object[]{bill_name,pro_name,date,quantity,cost});
            }
            total_transaction.setText(String.valueOf(total));
      
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    void bills()
    {
        sqlconnect sql=new sqlconnect();
        try
        {
        Connection con;    
        con=sql.Connections();
        Statement st=con.createStatement();
    String Query="select * from bill";
        ResultSet res = st.executeQuery(Query);
        
        while(res.next())
        {
            String list=res.getString("date");
            System.out.println(list);
            date_list.addItem(list);
        }
        
        }catch (Exception e) 
        {
        e.printStackTrace();
      
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales_Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Confirm_password;
    private javax.swing.JPasswordField Existing_password;
    private javax.swing.JPasswordField New_password;
    private javax.swing.JTable bill_table;
    private javax.swing.JComboBox date_list;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Button sal_man_reset2;
    private java.awt.Button sal_man_submit2;
    private javax.swing.JPanel sal_man_submit3;
    private javax.swing.JButton sel_man_no;
    private javax.swing.JButton sel_man_yes;
    private javax.swing.JLabel status1;
    private javax.swing.JLabel status2;
    private javax.swing.JLabel total_transaction;
    private javax.swing.JLabel total_transaction_per_day;
    private javax.swing.JTable transaction;
    // End of variables declaration//GEN-END:variables
}
